language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  - ORCHESTRA_VERSION=3.8.x
  - ORCHESTRA_VERSION=4.x
  - ORCHESTRA_VERSION=5.x
  - ORCHESTRA_VERSION=6.x

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction          
  - if [ "$ORCHESTRA_VERSION" != "" ]; then composer require --dev "orchestra/testbench:${ORCHESTRA_VERSION}" --no-update; fi;  
  - composer update
script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

notifications:
  email: false